services:

  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - laravel

  php:
    image: php:8.3-fpm
    container_name: php
    volumes:
      - ./laravel:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - laravel
    command: >
      sh -c "
          apt-get update &&
          apt-get install -y unzip curl git zip libpng-dev libonig-dev libxml2-dev libzip-dev libpq-dev default-mysql-client &&
          docker-php-ext-install mysqli pdo pdo_mysql &&
          php-fpm
        "

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: video_streamer
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel


  composer:
    image: composer:latest
    container_name: composer
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
    entrypoint: ["composer"]
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data: